---
- name: Install ZSH shell + custom config
  become: false
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}
    git clone https://github.com/Chibraax/make_my_shell
    ./make_my_shell/setup.sh
  args:
    creates: "/home/{{ ansible_user }}/.oh-my-zsh/themes/chibraax2.zsh-theme"
  tags: gen_config

- name: Add aliases inside .zshrc file For {{ username }}
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.zshrc
    line: "{{ item }}"
  loop: "{{ alias_config }}"
  tags:
    - gen_config

- name: Add aliases inside .zshrc file for ROOT user
  ansible.builtin.lineinfile:
    path: /root/.zshrc
    line: "{{ item }}"
  loop: "{{ alias_config }}"
  tags:
    - gen_config

- name: Set the hostname
  ansible.builtin.lineinfile:
    path: /etc/hostname
    regexp: '^.+'
    line: "{{ server_hostname }}"
  become: true
  notify: reboot
  tags:
    - gen_config

- name: Listen ssh Daemon on port 5656
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#Port 22'
    line: 'Port 5656'
  tags: gen_config

- name: Create .vimrc for ROOT user
  ansible.builtin.lineinfile:
    path: /root/.vim.rc
    line: "set number"
    create: true
    mode: '0600'
  become: true
  notify: reboot
  tags:
    - gen_config

- name: Create .vimrc for {{ username }} user
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.vim.rc
    line: "set number"
    create: true
    mode: '0600'
  become: false
  become_user: "{{ username }}"
  notify: reboot
  tags:
    - gen_config
